### PR TITLE
Implement configure method - Support to update the behaviour of a mock (part 2)

### PR DESCRIPTION
**Pull request by asiFarran**
This is mostly  the work of @notanengineercom from here: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/113

I just added some tests and some code for received call count handling for configured methods

With this implementation, the match order is slightly changing. When looking at the current readme it says:

The order of argument matchers matters. The first matcher that matches will always be used

This will not be enterly true from now on. The matches are now divided into three groups that have different priorities, depending on the arguments. The groups and priorities are defined as the following:

Arguments with primitives only group - calc.add(1, 2)
Arguments with at least 1 Argument instance - calc.add(Arg.any(), Arg.is(x => x > 0))
Arguments replaced by Arg.all - calc.add(Arg.all())
Inside these tree groups, the current match order is preserved (first match that gets defined, is the first one to be used if matched).
This means that now it's possible to first define a generic / default match, followed by a specific one:

```
calculator.add(Arg.all()).mimicks((a, b) => a + b)
calculator.configure().add(1, 1).returns(11)

console.log(calculator.add(90, 10)) // 100
console.log(calculator.add(1, 1)) // 11
```
Also reassigning the same match to different values

```
calculator.add(1, 1).returns(2)
console.log(calculator.add(1, 1)) // 2

calculator.configure().add(1, 1).returns(0)
console.log(calculator.add(1, 1)) // 0
```

Can also change result to an exception
```
calculator.configure().add(1, 1).throws(new Error('Change the number!'))
calculator.add(1, 1) // Error: Change the number!
```

TODO

- Documentation

### CODE REVIEW

**Comment by asiFarran** [comment]
Note that with regards to the discussion around the name of the method (i.e `configure`) I think it makes most sense to keep the name and use the same strategy used for the other potential clashes - `disableFor`

**Comment by notanengineercom** [comment]
Hi, thanks for your contribution!
We've been really busy lately this past year, so there has not been a lot of improvements in the repo.
But these past two weeks I've been working in the v2-beta branch locally, rewriting the logic to have an easier and more modular codebase, which will help in adding new features easily, and make the code really maintainable.

I think I need one more week tops to polish the details, and make it ready to be reviewed. So until then, I don't think we should merge the .configure() feature, which is why the pull request is still open.
I will leave this pull request open too and take a look tomorrow to review it!

**Comment by notanengineercom** [comment]
Hey, just took a look to the pull request!
.configure should not reset recorded calls - the only aim is to configure overlapping mocks, e.g: the example here: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/113

We will be adding .configure to v2, so I will close both this, and my pull request. I would like to use your `configure.spec` tests if you don't mind once we create the feature pull request (I will add you as co-author 😄)

> One more comment is that as I'm using this in my project I find that it might actually be more intuitive to make configure the only way to setup an explicit substitution.

Thanks for your input, but we want to try to be as close as possible to NSubstitute, and that would be a big deviation + a huge breaking change.
Nevertheless, you can use the convention you like the most in your project, so having .configure, will give you the option to set the mocks as you mentioned

**Comment by asiFarran** [comment]
> .configure should not reset recorded calls - the only aim is to configure overlapping mocks, e.g: the example here: #113

noted, though then another change would have to be made to how you manage recorded calls when configuring because with the current implementation which removes the 'last' recorded call as that leads to a wrong/confusing state after every time to you call `.configure`.

**Pull request closed without merging**
