### PR TITLE
fix: typescript 4.8

### LINKED ISSUE #241: Substitute.d.ts(6,35): error TS2344: Type 'T' does not satisfy the constraint 'Object'
**Describe the bug**

I am on version `1.208.0` using Typescript `4.8.3` and running `tsc` gives the following type error:

```
Error: node_modules/@fluffy-spoon/substitute/dist/src/Substitute.d.ts(6,35): error TS2344: Type 'T' does not satisfy the constraint 'Object'.
```

node_modules/@fluffy-spoon/substitute/dist/src/Substitute.d.ts Line 6:

image

### PR DESCRIPTION
**Pull request by AuHau**
Should close #241

### CODE REVIEW

**Comment by notanengineercom** [comment]
Hi! Thanks for your contribution.
I think the linked issue isn't reproduced in the beta release, and the code currently published in the main branch is for the beta release

**Comment by ffMathy** [comment]
We should really get the beta release out. Can't remember where we got to. Do you? What's missing?

**Comment by notanengineercom** [comment]
The

**Comment by notanengineercom** [comment]
The beta is released and published. The [last release](https://www.npmjs.com/package/@fluffy-spoon/substitute/v/2.0.0-beta.1) was 4 months ago

**Comment by ffMathy** [comment]
Yeah I just can't remember if we had anything to do before we consider it stable and release it as a full release (not beta).

Should we do that perhaps?

**Comment by AuHau** [comment]
The issue was reproduced on beta release. With bit different trace and not on one but two points, but still present. Will have a look tomorrow again to confirm.

**Comment by notanengineercom** [comment]
> Yeah I just can't remember if we had anything to do before we consider it stable and release it as a full release (not beta).
> 
> Should we do that perhaps?

Mainly a few features are missing, and I wanted to check if there were any issues with the new changes. I thought there weren't any, but with this latest issue, we should wait.
> The issue was reproduced on beta release. With bit different trace and not on one but two points, but still present. Will have a look tomorrow again to confirm.

Awesome, thanks!
I ran the build script locally, with typescript 4.8.4, and didn't get any complaints. If you could share a code sample, that would be highly appreciated 🙏

**Comment by AuHau** [comment]
Sorry about confusion, I meant TS 4.8 version and not 3.8 😅 🙈

**Comment by AuHau** [comment]
Hmm alright, I will try to create reproduction tomorrow.

**Comment by ffMathy** [comment]
@AuHau ever got the repro? ☺️

**Comment by notanengineercom** [comment]
This is no longer needed, so I will close for now. Fixed in https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/244

**Pull request closed without merging**
