### PR TITLE
Improve assertion messages when running expectations

### LINKED ISSUE #27: Unable to use mocks with angular TestBed
Love the simplicity of lib but im unable to use it in component testing with angular TestBed.

Test:

```
describe('FilterContentWidgetComponent', () => {
    let component: FilterContentWidgetComponent;
    let fixture: ComponentFixture<FilterContentWidgetComponent>;

    let filterMapperMock = Substitute.for<FilterMapper>();
    
    beforeEach(async() => {
        TestBed.configureTestingModule( {
            declarations: [ 
                FilterContentWidgetComponent,
            ],
            imports: [ HttpModule], 
            providers: [ 
                { provide: FilterMapper, useValue: <FilterMapper>filterMapperMock},
                
             ]
        }).compileComponents();
    });

    beforeEach(() => {
        fixture = TestBed.createComponent(FilterContentWidgetComponent);
        component = fixture.componentInstance;
      });

    it('should create', () => {
        fixture.detectChanges();

        expect(component).toBeTruthy();
    });
});
```

Not sure if am doing sth wrong but i get following exception. 

`
TypeError: Cannot convert object to primitive value
        at JitEmitterVisitor._emitReferenceToExternal (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4693:44)
        at JitEmitterVisitor.visitExternalExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4662:1)
        at ExternalExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:1293:1)
        at visitAllObjects.expr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4387:1)
        at JitEmitterVisitor.visitAllObjects (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4406:1)
        at JitEmitterVisitor.visitAllExpressions (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4387:1)
        at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4218:1)
        at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4547:1)
        at InvokeFunctionExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:1250:1)
        at visitAllObjects.expr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js?:4387:1)`

### LINKED ISSUE #138: `JSON.stringify()` does not play well
**Describe the bug**
When calling `JSON.stringify` on Substitute I will receive `undefined`. While I understand that it is hard to decide what should be returned I would expect at least something and not `undefined`.

I think that the `toJSON()` function could be employed here to define some behavior.

**To Reproduce**
```typescript
interface Obj {
	hello: string
}
const sub = Substitute.for<Obj>()
sub.hello.returns('world')
JSON.stringify(sub) // undefined
```

### LINKED ISSUE #140: Provide stack traces with "All calls received to method..."
**Is your feature request related to a problem? Please describe.**

When you assert the number of calls for some method in complex code and the assertions fail it might be hard from which part of the code these calls come.

**Describe the solution you'd like**

Store the stack traces for each call and upon failure of the assertion display them together with "-> call with arguments ..." messages.

**Describe alternatives you've considered**

No idea.

**Additional context**

A possible problem is how to present this information in order to avoid overwhelming the dev with too much information... Possible there could be either env. variable or a flag that would enable such behavior.

### PR DESCRIPTION
**Pull request by notanengineercom**
Showcases a draft on how to improve the readability and developer experience when evaluating assertions (received didNotReceive).
Originated from the suggestion in #140, with this addition, we'd be recording stack traces of where a call was made. I also tried to enrich the assertion failure description with information like what has been called, how and what's expected:

Screenshot 2024-03-10 at 00 43 41

Closes #140 
Closes #27 
Closes #138

### CODE REVIEW

**Comment by notanengineercom** [comment]
Tests for node.js 12, 14 and 16 fail just because the formatting of stack traces lines are slightly different than in the newer node.js versions  (>= 18).

**Comment by ffMathy** [comment]
Wow, this is an amazing addition! I am currently sick and have been for a week, but hope to contribute at a faster pace soon ❤️

**Comment by ffMathy** [comment]
Yeah let's just drop support for those older versions of node BTW.

18 and up should be fine.

**Comment by notanengineercom** [comment]
Thanks 😄
Alright, what do you think about following [node.js' release schedule](https://github.com/nodejs/release?tab=readme-ov-file#release-schedule)? That would mean (looking at April'24), we'd run the CI tests against versions 18, 20 and 22.
Get well soon 🫶🏼

**Comment by ffMathy** [comment]
> Thanks 😄 Alright, what do you think about following [node.js' release schedule](https://github.com/nodejs/release?tab=readme-ov-file#release-schedule)? That would mean (looking at April'24), we'd run the CI tests against versions 18, 20 and 22. Get well soon 🫶🏼

I love that strategy! Let's do that :heart:

Thank you!

**Comment by notanengineercom** [comment]
I made some changes to allow a bunch of serialization options:
- using console.log
- using JSON.stringify
- getting a primitive from substitute

It just generates a string with a simple tree of the substitution object (not exposing any internals)

**Pull request merged**
