### PR TITLE
Maintenance upgrades, guarantee support for node.js 18 & drop node.js 10

### PR DESCRIPTION
**Pull request by notanengineercom**
Some dependency maintenance and guarantee the support for node.js 18 by adding it to the test matrix

### CODE REVIEW

**Comment by notanengineercom** [comment]
Hmm this is annoying :/ Ava v4 drops support for node.js 10, so running the tests in Node.js 10 fails. We can do one of the following:
1. Revert Ava to v3?
2. Remove Node.js 10 from the test matrix?
3. Replace ava with another unit testing framework?

Using Node.js 10 is not limiting nor creating conflicts within our codebase, but in the other hand, it reached end of life one and a half years ago. @ffMathy what should we do?

**Comment by ffMathy** [comment]
I'm fine with whatever you believe in. Perhaps we could switch to Jest?

But either option is fine with me ❤️

**Review by ffMathy — APPROVED** [review]

**Comment by notanengineercom** [comment]
Jest requires at least node 14 haha 😅
Let me check for other unit testing options, I'd like to keep Node.js 10 as long as it doesn't cause any big inconveniences.

**Comment by ffMathy** [comment]
Hmmm. I think dropping node 10 is okay as it has end of life. If people then need it, they can use an older version of substitute-JS 😊

But yeah feel free to explore more options 🙏

**Comment by notanengineercom** [comment]
I dropped node 10. I didn't find anything that could have worked nicely with node 10 except [QUnit](https://github.com/qunitjs/qunit), but I don't think it was the effort to switch to it.

**Pull request merged**
