### PR TITLE
59 test commented

### PR DESCRIPTION
**Pull request by IlhamKhabibullin**

### CODE REVIEW

**Comment by IlhamKhabibullin** [comment]
@ffMathy

**Comment by IlhamKhabibullin** [comment]
seems like test was not working in that pr already https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/commit/92f7e60b871714f60ace5bb3ddc7ce6d5e0908ac

**Comment by ffMathy** [comment]
Is there a way we can make it work though? The PR was merged on purpose despite failing tests, so that I would remember to fix it next time.

**Comment by IlhamKhabibullin** [comment]
How about logging WARN instead? There are some complicated typescript stuff like `infern`. Don't know how it works

**Comment by ffMathy** [comment]
That's okay. We'll skip it for now.

**Comment by IlhamKhabibullin** [comment]
do you upgrade version in package.json? or smthin
my main question is how it will be published to npm, and how can I download
latest version


ср, 13 нояб. 2019 г. в 15:05, Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by ffMathy** [comment]
It has just been published.

https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/releases

**Comment by IlhamKhabibullin** [comment]
oh, yeah i see, thank you 👏

ср, 13 нояб. 2019 г. в 16:01, Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by ffMathy** [comment]
No, thank YOU ;)

**Pull request merged**
